-- (c) 2021 by SwordLord - the coding crew
-- Add this script to your Aseprite Sprite Editor. With this script you can export your sprites to their cpp representation.
--
-- This file is part of the SwordLord DANG! Game Framework. DANG! is made for the 32blit Gaming Hardware.

-- functions

-- actual script

-- Make sure that there is an active image
local spr = app.activeSprite
if not spr then
  return app.alert("There is no active sprite")
end

-- make sure the image is in colormode indexed, having a palette
local colorMode = spr.colorMode
if colorMode ~= ColorMode.INDEXED then
    -- todo: change mode only after asking the user and she says OK
    app.alert("Image does not have indexed colours. Trying to change that. Make sure to save the image afterwards if you want to keep changes.")
    app.command.ChangePixelFormat{ format="indexed", dithering="none" }
end

-- make sure there is an active image
local img = app.activeImage
if not img then
    return app.alert("There is no active image")
end

-- todo: make sure that there is only one palette or ask the user
local palette = spr.palettes[1]

-- how many colours are there in the palette?
local colourCount = #palette
--app.alert(ncolors)

-- todo: ask the user what name she wants to store the export under
local filename = spr.filename -- :split(".")[1]
filename = filename .. ".h"

-- prepare file to be written into
local f = io.open(filename, "w")
io.output(f)

-- append standard header
io.write("// This file is auto generated by the SwordLord DANG Aseprite Exporter.\n")
io.write("// It will get overwritten once you re-export your sprites!\n")
io.write("// (c) 2021 by SwordLord - the coding crew\n")
io.write("\n")

io.write(string.format("palette = Palette[%d];\n", colourCount))

for i = 0,#palette-1 do
  	local color = palette:getColor(i)
  	--print("r:" .. color.red .. " g:" .. color.green .." b:" .. color.blue .. " a:" .. color.alpha )
	io.write(string.format("palette[%d] = blit::Pen(%d, %d, %d, %d);\n", i, color.red, color.green, color.blue, color.alpha))
end

io.write("\n")

io.write(string.format("spriteWidth = %d;\n", spr.width))
io.write(string.format("spriteHeight = %d;\n", spr.height))

io.write("\n")

io.write("sprite.data = {\n")

for h = 0, img.height-1, 1 do
    for w = 0, img.width-1, 1 do

        io.write(string.format("%d,", img:getPixel(w, h)))

        if w % 8 == 0 then
            io.write("\n") -- todo remove ugly hack
        end

    end
    io.write("\n") -- todo remove ugly hack
end

io.write("}\n")

io.close(f)

return app.alert("Written your file: " .. filename)
