-- (c) 2021 by SwordLord - the coding crew
-- Add this script to your Aseprite Sprite Editor. With this script you can export your sprites to their cpp representation.
--
-- This file is part of the SwordLord DANG! Game Framework. DANG! is made for the 32blit Gaming Hardware.

-- functions

-- actual script

-- Make sure that there is an active image
local spr = app.activeSprite
if not spr then
  return app.alert("There is no active sprite")
end

-- make sure the image is in colormode indexed, having a palette
local colorMode = spr.colorMode
if colorMode ~= ColorMode.INDEXED then
    -- todo: change mode only after asking the user and she says OK
    app.alert("Image does not have indexed colours. Trying to change that. Make sure to save the image afterwards if you want to keep changes.")
    app.command.ChangePixelFormat{ format="indexed", dithering="none" }
end

-- make sure there is an active image
local img = app.activeImage
if not img then
    return app.alert("There is no active image")
end

-- todo: make sure that there is only one palette or ask the user
local palette = spr.palettes[1]

-- how many colours are there in the palette?
local colourCount = #palette
--app.alert(ncolors)

-- todo: ask the user what name she wants to store the export under

local outfile = spr.filename .. ".h" -- :split(".")[1]

if app.params["output_file"] ~= nil then
    outfile = app.params["output_file"]
end

-- prepare file to be written into
local f = io.open(outfile, "w")
io.output(f)

-- set default
-- todo: choose something sensible here. like file name without path or such
local symbol_name = outfile

if app.params["symbol_name"] ~= nil then
    symbol_name = app.params["symbol_name"]
end

-- append standard header
io.write("// This file is auto generated by the SwordLord DANG Aseprite Exporter.\n")
io.write("// It will get overwritten once you re-export your sprites!\n")
io.write("// (c) 2021 by SwordLord - the coding crew\n")
io.write("\n")
io.write("#include <32blit.hpp>\n")
io.write("#include <ImageImport.h>\n")
io.write("\n")

io.write(string.format("static dang::image_import %s\n", symbol_name))
io.write("{\n")

-- alpha
io.write(string.format("    uint8_t{%d},\n", 255))
-- bounds
io.write(string.format("    blit::Size{%d, %d},\n", spr.width, spr.height))
-- data
io.write("  std::vector<uint8_t>\n")
io.write("  {\n")

local counter = 0
local counterMax = (img.height) * (img.width)

for h = 0, img.height-1, 1 do
    for w = 0, img.width-1, 1 do

        if counter >= counterMax-1 then
            -- last line, no comma
            io.write(string.format("%d", img:getPixel(w, h)))
        else
            io.write(string.format("%d,", img:getPixel(w, h)))
        end

	    counter = counter + 1
        if counter % 40 == 0 then
            io.write("\n") 
        end
    end
end
io.write("  },\n")

-- palette
io.write("  std::vector<blit::Pen>\n")
io.write("  {\n")

local iPaletteCount = #palette

for i = 0,iPaletteCount-1 do
  	local color = palette:getColor(i)
  	--print("r:" .. color.red .. " g:" .. color.green .." b:" .. color.blue .. " a:" .. color.alpha )
	if i < iPaletteCount-1 then
		io.write(string.format("    blit::Pen(%d, %d, %d, %d),\n", color.red, color.green, color.blue, color.alpha))
	else
		-- last line, no comma
		io.write(string.format("    blit::Pen(%d, %d, %d, %d)\n", color.red, color.green, color.blue, color.alpha))
	end
end

io.write("  }\n")
io.write("};\n")
io.write("\n")
io.write("// EOF\n")

io.close(f)

print("Written your file to: " .. outfile)
--return app.alert("Written your file: " .. filename)
